const MAX_INPUT_LENGTH = 4;

const MIN_ARR_NUMBER = 0;
const MAX_ARR_NUMBER = 100;
const MIN_ARR_LENGTH = 3;
const ARR_LENGTH = 4;
const MAX_ARR_LENGTH = 6;

export {
  ARR_LENGTH,
  MIN_ARR_NUMBER,
  MAX_ARR_NUMBER,
  MIN_ARR_LENGTH,
  MAX_ARR_LENGTH,
  MAX_INPUT_LENGTH,
};
